#!ruby

$LOAD_PATH << "#{File.dirname(__FILE__)}/lib"

# This is for a crash in any thread to crash the whole program
$DEBUG = true

require 'optparse'
require 'server'
require 'hash_ext'

class Settings
  def start_nb_clients
    100
  end

  def generate_client_storage
    10
  end

  def generate_next_spawn_clients_time
    1
  end

  def generate_nb_clients_to_spawn
    2
  end

  def generate_next_add_file_time
    1
  end

  def generate_add_file_args
    [[1], [2]]
  end
end

opts = OptionParser.new do |opts|
  LOG.types.each do |k,v|
    opts.on("--[no-]log-#{k.to_s.gsub('_', '-')}", "Log the #{k} type") do |b|
      LOG.types[k] = b
    end
  end
  opts.on("-l x,y,z", Array, "Show log types") do |list|
    list.each { |a| LOG.types[a.to_s.gsub("-", "_").to_sym] = true }
  end
  opts.on("-h x,y,z", Array, "Hide log types") do |list|
    list.each { |a| LOG.types[a.to_s.gsub("-", "_").to_sym] = false }    
  end
end

opts.parse(ARGV)

server = Server.new Settings.new

server.run
