#!ruby

$LOAD_PATH << "#{File.dirname(__FILE__)}/lib"

# This is for a crash in any thread to crash the whole program
$DEBUG = true

require 'server'

class Settings
  def start_nb_clients
    100
  end

  def generate_client_storage
    10
  end

  def generate_next_spawn_clients_time
    1
  end

  def generate_nb_clients_to_spawn
    2
  end

  def generate_next_add_file_time
    1
  end

  def generate_add_file_args
    [[1], [2]]
  end
end

server = Server.new Settings.new

server.run
