#!ruby

$LOAD_PATH << "#{File.dirname(__FILE__)}/lib"

$DEBUG = true

require 'server'

class Settings
  def nb_clients
    100
  end

  def generate_client_storage
    10
  end

  def generate_next_add_file_time
    1
  end

  def generate_add_file_args
    [[1], [1]]
  end
end

server = Server.new Settings.new

server.run
